# Generated by Django 4.1.2 on 2023-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=138)),
                ('author', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('image_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
