# Generated by Django 4.2.2 on 2023-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_user_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='items', to='store.quantity'),
        ),
    ]
