# Generated by Django 4.2.2 on 2023-07-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_remove_quantity_price_cart_total_alter_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="grade",
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("english", "english"),
                    ("arabic", "arabic"),
                    ("maths", "maths"),
                ],
                default=("arabic", "arabic"),
                max_length=138,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("government", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=64)),
                ("ordered", models.BooleanField(default=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_order",
                        to="store.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=64)),
                ("books", models.ManyToManyField(related_name="bc", to="store.book")),
            ],
        ),
    ]
